name: CI

on: [push]

env:
  CR_REPO: commission_calculator
  TAG: latest
  
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Python dependencies
      run: |
        python -m pip install -r requirements.txt
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
        pip install black==23.12.0
    - name: Analysing the code with pylint
      run: |
        black --diff --check $(git ls-files 'commission_calculator/*.py')
        pylint --rcfile=.pylintrc $(git ls-files 'commission_calculator/*.py')

  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
        #cache: 'pip'
    - name: Install Python dependencies
      run: |
        pip install -r requirements.txt
        pip install .
    - name: Test
      run: |
        pytest test

  publish-docker-image:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.PUBLISH_TOKEN }}
    - name: Build Docker image
      run: |
            docker build . -t ghcr.io/angusll/$CR_REPO:$TAG
            docker push ghcr.io/angusll/$CR_REPO:$TAG